"""Changing datetime implementation to be default per table

Revision ID: 2abbc6a0260f
Revises: 37f145a2c419
Create Date: 2023-10-20 20:32:16.429992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2abbc6a0260f'
down_revision = '37f145a2c419'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calculations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))

    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))

    with op.batch_alter_table('incomes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incomes', schema=None) as batch_op:
        batch_op.drop_column('timestamp')

    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.drop_column('timestamp')

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_column('timestamp')

    with op.batch_alter_table('calculations', schema=None) as batch_op:
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
