"""Added '£'

Revision ID: d1ad46f25efa
Revises: 4ae0dcd8aaa8
Create Date: 2023-10-21 19:16:31.434830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1ad46f25efa'
down_revision = '4ae0dcd8aaa8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.Float(), nullable=False))
        batch_op.drop_column('value')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('value', sa.FLOAT(), nullable=False))
        batch_op.drop_column('amount')

    # ### end Alembic commands ###
